name: build

on:
  push:
    branches: '**'

jobs:
  build:
    name: ${{ matrix.os }}-build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [
            ubuntu-latest,
            macos-latest,
            windows-latest
        ]
        include:
          - os: windows-latest
          # includes
          - os: ubuntu-latest
          - os: macos-latest

    env:
      VCPKG_FEATURE_FLAGS: manifests,versions,registries
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: 'microsoft/vcpkg'
          path: ${{ github.workspace }}/vcpkg

      # Install latest CMake.
      - uses: lukka/get-cmake@latest

      - run: ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh
        if: matrix.os != 'windows-latest'

      - run: ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.bat
        if: matrix.os == 'windows-latest'

      - run: cmake ${{ github.workspace }} -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
